### ISSUE TITLE
Notification emails "Queued"

### ISSUE THREAD

**Issue by Ghitafjorback** [Basico-PS/AutomationOrchestrator#37]
Hi,
Is there any reason that the notification email about a script being queued will come no matter if a script is "actually" queued or not?
If nothing is running on the BOT, I will receive a notificatoin that the triggered Botflow is queued, and seconds later I will receive a notification email that they Botflow is started.
I believe it would be more usefull if the email notification saying that the Botflow is queued will only come when the botflow is acutally queued due to another botflow being in process.
Thanks
Ghita

**Comment by mbalslow** [comment]
Hi @Ghitafjorback,

Your request makes sense, however, it is not quite possible to implement. In theory, it could be implemented that before sending the email stating that the bot is now in the queue, it could check if nothing is already running (because if not, it should be assumed that it will start right away). However, the problem is that in a case where the job is put in the queue for another bot to run the job where there is not already something running, it could be the case that the particular bot is shutdown, meaning that the job will never start.

So I now that it is a bit of an email spam situation in those cases where the bot is queued and then started more or less right after, but that is by design.
