### ISSUE TITLE
Cant find mapped network drives

### ISSUE THREAD

**Issue by nmorck** [Basico-PS/AutomationOrchestrator#4]
Sometimes when executing a scheduled scripts from a mapped network drive, the Orchestrator says that it can't find the botflow. 
But if i use the UNC path for the drive there is no problems. 

Fx.

Not working: T:\Robotics Monitor v5.9.3 Scott Evil.rpa
Working: \\basicofil01\bco\\Robotics Monitor v5.9.3 Scott Evil.rpa

The error only occurs on some machines/drives. I have a suspicion that it could have something with the user rights to do.

**Comment by mbalslow** [comment]
Hi @nmorck,

Great input and feedback. I have classified this as an enhancement, I will look to implement a "test feature" similar to the triggers so that the user can test whether the specified path of the Botflow is valid or not. This way, you can detect the issue at the very beginning of the setup.

**Comment by mbalslow** [comment]
Implemented in the latest release [v0.1.2](https://github.com/Basico-PS/AutomationOrchestrator/releases/tag/v0.1.2)
