### ISSUE TITLE
Python window run as minimized

### ISSUE THREAD

**Issue by Ghitafjorback** [Basico-PS/AutomationOrchestrator#41]
Hi,
Not sure if this is possible at all, but if so, it would be nice that the task that runs the python script will run as "minimized" automatically. I mean instead of the window popping up once logon or fresh start.
If possible even as "hidden"
Thanks
Ghita

**Comment by mbalslow** [comment]
Hi @Ghitafjorback,

It will not be possible to have it run automatically minimized, however, it will be possible to run it "hidden" using pythonw.exe instead of the standard python.exe.

This will require enhancements to the code in three sections:
- The user should be able to choose when running the SET_RUN_SERVER.bat
- If the user decides to run it "hidden", the created job in the Task Scheduler should run the program using pythonw.exe instead of the standard python.exe
- No matter what, in the run_server.py file, it should use pythonw.exe instead of the standard python.exe

**Comment by Ghitafjorback** [comment]
Hi @mbalslow 
If I understand you correctly, the enhancement would mean that the checkmark in task scheduler "Hidden" will be checked? I tested that, and this is resulting in the python window still showing up, only the "code" or "text" within the python window is not visible.
Did I maybe misunderstand you?
I tried as well in the task scheduler to change the path to python.exe to pythonw.exe... this as well is resulting in the window still to show up, but the code/text is not visible.
Thanks
Ghita

**Comment by mbalslow** [comment]
Solved by [this commit](https://github.com/Basico-PS/AutomationOrchestrator/commit/d2ddddedb42fd8a42368a08a9c17bacbb83da15f) and will be available in the upcoming [v0.3.5](https://github.com/Basico-PS/AutomationOrchestrator/releases/tag/v0.3.5)

**Comment by Ghitafjorback** [comment]
I love the new update with the Orchestrator python window being hidden! Thank you so much for the update!
