### ISSUE TITLE
Starting botlows manually

### ISSUE THREAD

**Issue by andriussi** [Basico-PS/AutomationOrchestrator#46]
Hi
It could be just me, but I find it a bit confusing with the name of the option 'activate selected triggers'. 
![image](https://user-images.githubusercontent.com/64826914/83111579-834fb400-a0cd-11ea-8430-32893834ff6c.png)

Since there is a column 'Activated' my first though was that if I click that it will just mark all of the botflows as activated, but instead it is for starting it. Maybe the 'Activate' word could be changed to 'Start' or 'Run'?

Also, it would be nice to be able to run the flow manually directly from the 'Botflow' window and not only from scheduled windows. 
![image](https://user-images.githubusercontent.com/64826914/83111610-8e0a4900-a0cd-11ea-8842-d98c280fd6d9.png)

**Comment by mbalslow** [comment]
Hi @andriussi,

I do agree with you feedback on the naming of the action. I have implemented this change + some general code cleanup in this commit https://github.com/Basico-PS/AutomationOrchestrator/commit/8c7469390973b46e2017d0dc90c97654972be23b and it will be available in the next release.

On the request of a similar action in the Botflow view, this is possible, however, it does require some leg-work. The reason for this is that in order to start a Botflow, you need to specify the Bot that is supposed to run the job. That is already done when setting up the triggers, therefore, it is not an issue on those pages. To implement it on the Botflow page, I would need to develop an [intermediate page](https://docs.djangoproject.com/en/3.0/ref/contrib/admin/actions/#actions-that-provide-intermediate-pages) that the user is redirected to when activating the "Run selected botflows" action where the user should be offered a list of all available bots for the user to select one of them to run the job(s) selected to be started. I hope that makes sense and makes it clear why it requires some leg-work to implement. I will add this to my wishlist as a nice-to-have item.

**Comment by andriussi** [comment]
Thanks for chaning the names :)

Regarding your other explanation, it does make total sense. I didn't consider that fact. 
What about adding a field when creating a botflow to select default app and you could run on that. And then when you add it to scheduled trigger or file trigger, it would be overwritten with the app selected there. Or this would also require a lot of change?

**Comment by mbalslow** [comment]
Hi @andriussi,

That workaround could potentially work, however, it would definitely be best to do as mentioned and develop an intermediate page. It is not that it will require tons of work, it just requires a bit more than what I could quickly do before making the next release. So I will add this to my wishlist as a nice-to-have item and develop it when I find the time.
